import { StyleSheet } from 'react-native';

const baseTextStyle = {
    fontFamily: 'Pretendard', 
  };
  
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#1c1c1c',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      paddingVertical: 10,
      paddingHorizontal: 20,
      zIndex: 10,
      position: 'absolute',
      top: 40,
      left: 0,
      right: 0,
    },
    coinContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 4,
      marginRight: 'auto',
    },
    coinIcon: {
      width: 24,
      height: 24,
    },
    smallCoinIcon: {
      width: 20,
      height: 20,
      marginRight: 4,
    },
    coinText: {
      ...baseTextStyle,
      fontSize: 20,
      fontWeight: '500',
      color: 'white',
      marginLeft: 3,
      lineHeight: 22,
      textAlign: 'center',
    },
    scrollContainer: {
      paddingBottom: 150, 
    },
    imageHeader: {
      width: '100%',
      height: 300,
      position: 'relative',
    },
    backgroundImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    favoriteIcon: {
      position: 'absolute',
      bottom: 10,
      right: 20,
      flexDirection: 'row',
      alignItems: 'center',
    },
    favoriteButton: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    favoriteCount: {
      ...baseTextStyle,
      fontSize: 16,
      color: 'black',  
      marginLeft: 4,
    },
    userContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      backgroundColor: '#1c1c1c',
      paddingHorizontal: 20,
    },
    userIconContainer: {
      backgroundColor: 'white',
      borderRadius: 20,
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
    },
    userIcon: {
      borderRadius: 20,
    },
    username: {
      ...baseTextStyle,
      fontSize: 16,
      fontWeight: '600',
      color: '#FCFCFC',
      lineHeight: 20,
      fontStyle: 'normal',
    },
    location: {
      ...baseTextStyle,
      fontSize: 12,
      fontWeight: '600',
      color: '#CCC',
      lineHeight: 16,
      fontStyle: 'normal',
      marginTop: 4,
    },
    infoContainer: {
      marginLeft: 'auto',
      alignItems: 'flex-end',
      flexDirection: 'column',
    },
    coinInfoContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
      alignSelf: 'flex-start',
    },
    infoText: {
      ...baseTextStyle,
      fontSize: 14,
      color: 'white',
    },
    dateContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
    },
    smallCalendarIcon: {
      marginRight: 4,
      width: 20,
      height: 20,
    },
    separatorLine: {
      height: 1,
      backgroundColor: '#FFD700',
      marginHorizontal: 0,
      marginBottom: 16,
    },
    detailsContainer: {
      padding: 16,
      paddingHorizontal: 20,
    },
    title: {
      ...baseTextStyle,
      fontSize: 17,
      fontWeight: '500',
      color: '#FFF',
      lineHeight: 22,
      fontStyle: 'normal',
      marginBottom: 8,
    },
    tagContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    tag: {
      display: 'flex',
      paddingVertical: 3,
      paddingHorizontal: 12,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
      backgroundColor: 'rgba(252, 220, 42, 0.20)',
      marginRight: 4,
    },
    tagText: {
      color: '#FCDC2A',  
      textAlign: 'center',
      fontFamily: 'Pretendard-Regular',
      fontSize: 12,
      fontStyle: 'normal',
      fontWeight: '600',
      lineHeight: 18,
    },
    description: {
      ...baseTextStyle,
      fontSize: 16,
      color: '#FFFFFF',
      marginBottom: 16,
    },
    chatButton: {
      backgroundColor: '#FFD700',
      height: 70,
      borderTopLeftRadius: 15,
      borderTopRightRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      borderTopColor: '#000',
      borderLeftColor: '#000',
      borderRightColor: '#000',
      borderTopWidth: 2,
      borderLeftWidth: 2,
      borderRightWidth: 2,
      width: '100%', 
      position: 'absolute',
      bottom: 0,
    },
    chatButtonText: {
      ...baseTextStyle,
      color: '#333',
      fontSize: 32,
      fontWeight: '600',
      textAlign: 'center',
      lineHeight: 40, 
    },
  });

  export default styles;