import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: '#000',
    marginTop: 40,
  },
  pageTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
    marginRight: -24,
    fontFamily: 'Pretendard-Bold',
  },
  profileSection: {
    marginTop: 24,
    paddingHorizontal: 20,
  },
  profileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 10,
    paddingLeft: 0,
  },
  profilePicture: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#D9D9D9',
    marginRight: 10,
  },
  userInfo: {
    flex: 1,
    height: 45,
    justifyContent: 'center',
    marginRight: 20,
  },
  name: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    lineHeight: 22,
    marginBottom: 5,
    fontFamily: 'Pretendard-Bold',
  },
  class: {
    color: '#ccc',
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Pretendard-Regular',
  },
  pointsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  coinIcon: {
    width: 24,
    height: 24,
    marginRight: 4,
  },
  pointsText: {
    color: '#FCFCFC',
    textAlign: 'center',
    fontFamily: 'Pretendard',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '800',
    lineHeight: 22,
  },
  profileButton: {
    width: '100%',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#171717',
    borderRadius: 4,
    marginTop: 10,
    marginBottom: 24,
  },
  profileButtonText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Pretendard',
    fontWeight: '700',
  },
  activitySection: {
    marginTop: 20,
    paddingHorizontal: 20,
  },
  activityTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    fontFamily: 'Pretendard-Bold',
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  activityText: {
    color: '#fff',
    fontSize: 14,
    marginLeft: 10,
    fontFamily: 'Pretendard-Regular',
  },
  accountSection: {
    marginTop: 40,
    paddingHorizontal: 20,
  },
  accountTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    fontFamily: 'Pretendard-Bold',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  logoutText: {
    color: '#fff',
    fontSize: 14,
    marginLeft: 10,
    fontFamily: 'Pretendard-Regular',
  },
});

export default styles;
